Repository ODINN-SciML/ODINN.jl, pull requests merged in 2025-04, with the labels that each got.

#268 Add VJP benchmark in CI
  .github/workflows/CI.yml
  .gitignore
  benchmark/run.jl
  src/setup/config.jl
  src/simulations/functional_inversions/functional_inversion_utils.jl
  test/runtests.jl
Labels: enhancement

#296 Increase distance_to_border in halfar tests to reduce the error
  test/runtests.jl
  test/test_grad_loss.jl
Labels: bug

#300 Improve Continuous VJP computation
  src/inverse/SIA2D_adjoint.jl
  test/runtests.jl
Labels: math

#299 Functional inversion tutorial
  docs/Manifest.toml
  docs/Project.toml
  docs/make.jl
  docs/makeLocal.jl
  docs/src/doc_utils.jl
  docs/src/forward_simulation.jl
  docs/src/funcs_types.md
  docs/src/functional_inversion.jl
  docs/src/tutorials.jl
  scripts/MWEs/MWE_custom_adjoint.jl
  src/inverse/gradient.jl
  src/models/machine_learning/ML_utils.jl
  src/setup/config.jl
Labels: bug, performance

#294 Ice velocity integration
  Project.toml
  benchmark/run.jl
  docs/src/functional_inversion.jl
  scripts/MWEs/MWE_custom_adjoint.jl
  scripts/sensealg_benchmark.jl
  src/inverse/gradient.jl
  src/models/machine_learning/ML_utils.jl
  src/simulations/functional_inversions/functional_inversion_utils.jl
  test/PDE_UDE_solve.jl
  test/SIA2D_adjoint.jl
  test/test_grad_Enzyme.jl
  test/test_grad_loss.jl
Labels: enhancement
